version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg17  # Use pgvector with PostgreSQL 17
    container_name: postgres_pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data  # Persistent storage

volumes:
  pgvector_data:  # Named volume for persistence
